namespace DynaBee.Testing;

using System.Reflection;
using System.Text;

internal static class DynaBeeGeneratedSourceWriter
{
    public static string WriteType(ITypeContext typeContext)
    {
        var type = typeContext?.ClrType ?? throw new ArgumentNullException(nameof(typeContext));
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// DynaBee generated type snapshot for tests.");
        builder.AppendLine();

        foreach (var metadata in typeContext.Metadata.OrderBy(x => x.Key, StringComparer.Ordinal))
            builder.AppendLine($"// metadata: {metadata.Key} = {metadata.Value}");

        var kind = type.IsInterface ? "interface" : type.IsEnum ? "enum" : type.IsValueType ? "struct" : "class";
        var inheritance = BuildInheritance(type);
        builder.AppendLine($"public {kind} {type.Name}{inheritance}");
        builder.AppendLine("{");

        var bindingFlags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;

        foreach (var constructor in type.GetConstructors(bindingFlags).OrderBy(x => x.GetParameters().Length))
            builder.AppendLine($"    {GetAccess(constructor)} {type.Name}({FormatParameters(constructor.GetParameters())});");

        foreach (var property in type.GetProperties(bindingFlags).OrderBy(x => x.Name, StringComparer.Ordinal))
            builder.AppendLine($"    {FormatProperty(property)}");

        foreach (var method in type.GetMethods(bindingFlags).Where(x => !x.IsSpecialName).OrderBy(x => x.Name, StringComparer.Ordinal))
            builder.AppendLine($"    {GetAccess(method)} {GetTypeName(method.ReturnType)} {method.Name}({FormatParameters(method.GetParameters())});");

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string BuildInheritance(Type type)
    {
        var bases = new List<string>();
        if (type.BaseType != null && type.BaseType != typeof(object) && !type.IsValueType && !type.IsInterface)
            bases.Add(GetTypeName(type.BaseType));

        bases.AddRange(type.GetInterfaces().Select(GetTypeName).OrderBy(x => x, StringComparer.Ordinal));
        return bases.Count == 0 ? string.Empty : " : " + string.Join(", ", bases);
    }

    private static string FormatProperty(PropertyInfo property)
    {
        var getter = property.GetGetMethod(true) != null ? "get; " : string.Empty;
        var setter = property.GetSetMethod(true) != null ? "set; " : string.Empty;
        var accessor = getter + setter;
        return $"{GetAccess(property.GetMethod ?? property.SetMethod)} {GetTypeName(property.PropertyType)} {property.Name} {{ {accessor}}}";
    }

    private static string FormatParameters(IEnumerable<ParameterInfo> parameters)
        => string.Join(", ", parameters.Select(x => $"{GetTypeName(x.ParameterType)} {x.Name}"));

    private static string GetTypeName(Type type)
    {
        if (!type.IsGenericType)
            return type.Name;

        var name = type.Name.Split('`')[0];
        return $"{name}<{string.Join(", ", type.GetGenericArguments().Select(GetTypeName))}>";
    }

    private static string GetAccess(MethodBase member)
    {
        if (member == null) return "private";
        if (member.IsPublic) return "public";
        if (member.IsFamily) return "protected";
        if (member.IsAssembly) return "internal";
        if (member.IsFamilyOrAssembly) return "protected internal";
        if (member.IsFamilyAndAssembly) return "private protected";
        return "private";
    }
}
