<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>DynaBee</PackageId>   
    <Description>DynaBee is a lightweight .NET library that leverages Reflection.Emit to dynamically generate types at runtime.</Description>
    <PackageTags>emit il runtime dynamic-types code-generator dynabee elysium</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
    <PackageReference Include="MinVer" Version="6.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DependencyInjection\" />
  </ItemGroup>

</Project>
